---

- name: Copying files
  hosts: all
  become: true
  
  tasks:
  - name: copy file to target servers
    copy:
      src: "../assets/index.html"
      dest: "/var/www/html/index.html"
      owner: ubuntu
      group: ubuntu
      mode: u+x
      backup: true