---
- name: Install and Start Service
  hosts: Role_web
  become: true

  tasks:

  - name: Update apt cache "sudo apt  update"
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name: nginx
      state: present
    notify: Restart Service
  
  handlers:
  - name: Restart Service
    service:
      name: nginx
      state: started
      enabled: true